#!/usr/bin/env ruby

git_bundles = %w{
  git://github.com/scrooloose/nerdtree.git

  git://github.com/tpope/vim-fugitive.git
  git://github.com/tpope/vim-repeat.git
  git://github.com/tpope/vim-surround.git

  git://github.com/vim-scripts/buftabs.git
  git://github.com/vim-scripts/CmdlineComplete.git
  git://github.com/abudden/TagHighlight.git
  git://github.com/garbas/vim-showmarks.git

  git://github.com/garbas/vim-snipmate.git
  git://github.com/MarcWeber/vim-addon-mw-utils.git
  git://github.com/tomtom/tcommand_vim.git
  git://github.com/tUrG0n/snipmate-snippets.git
}

require 'fileutils'
require 'open-uri'

bundles_dir = File.join(File.dirname(__FILE__), "bundle")

FileUtils.rm_rf(bundles_dir)
FileUtils.mkdir(bundles_dir)
FileUtils.cd(bundles_dir)

git_bundles.each do |url|
  puts url
  `git clone -q #{url}`
end

Dir["*/.git"].each {|f| FileUtils.rm_rf(f) }
